### ISSUE TITLE
StreamOrder is not always an integer

### ISSUE THREAD

**Issue by plondino** [MediaArea/MediaAreaXml#73]
I am trying to parse an XML generated from a transport stream, and the `StreamOrder` element is a string, not an integer:

```        
<track type="Video">
            <StreamOrder>0-0</StreamOrder>
...
```

Per the schema:

`<xsd:element name="StreamOrder" minOccurs="0" maxOccurs="1" type="xsd:integer"/>`

Does the schema need to be updated or is this an issue with the parsing?

Full XML:
[media info 24.01.1.xml.txt](https://github.com/MediaArea/MediaAreaXml/files/14984093/media.info.24.01.1.xml.txt)

**Comment by JeromeMartinez** [comment]
> Does the schema need to be updated or is this an issue with the parsing?

The schema needs to be updated because in some cases it is 2 integers separated by a dash.
For e.g., it is (0-based) the position of the program in the PAT, dash, the position on the track in the PMT.
It would deserve a different way for having it in the XML but for the moment it is the one common to text, HTML, XML, JSON, etc.
